### ISSUE TITLE
Unit 1 Glossary Markov Property

### ISSUE THREAD

**Issue by andraxin** [huggingface/deep-rl-class#121]
The definition feels a bit backwards, considering that the **agent**
can _always_ decide to act based only on the current state, but
whether or not that can be optimal depends on the **environment**,
or its state progression to be precise, satisfies a  Markov property.

**Comment by simoninithomas** [comment]
Hey there 👋 ,

Thanks for your feedback 🤗

Indeed Markov Property is in the state I'm agree with you.

A state signal that succeeds in retaining all relevant information is said to be Markov, or to have the Markov property (we define this formally below). For example, a checker's position--the current configuration of all the pieces on the board--would serve as a Markov state because it summarizes everything important about the complete sequence of positions that led to it. Much of the information about the sequence is lost, but all that really matters for the future of the game is retained.

But what we mention here is that it implies then that our agent needs only the current state. As mentioned in the course "In papers, you’ll see that the RL process is called the Markov Decision Process (MDP). We’ll talk again about the Markov Property in the following units."  

I'm adding the Sutton chapter to the reading lists.

Thanks 🤗

**Comment by andraxin** [comment]
@simoninithomas 
> But what we mention here is that it implies then that our agent needs only the current state. 

You may want to check again, as that's not what your definition says.
https://github.com/huggingface/deep-rl-class/blob/main/units/en/unit1/glossary.mdx#markov-property

**Comment by osanseviero** [comment]
(FYI, the glossary is community contributed, not created by the HF team. You can also feel free to open a PR to update the glossary if you want to do so :) )
