### ISSUE TITLE
Unit 1 Quiz Q3 wrong answer expected

### ISSUE THREAD

**Issue by andraxin** [huggingface/deep-rl-class#122]
Given only the current board position, [chess](https://en.wikipedia.org/wiki/Rules_of_chess) is only partially observable,
since state that affects the set of possible next moves (namely, [caslting](https://en.wikipedia.org/wiki/Castling)
and [en passant](https://en.wikipedia.org/wiki/En_passant)) cannot always be determined from the board alone.

---
- [x] We receive an observation when we play with chess environment
Incorrect. Since we have access to the whole checkboard information.
---

BTW, the difference between observation and state sought after here is _questionable_.
See https://github.com/huggingface/deep-rl-class/issues/123

**Comment by simoninithomas** [comment]
Hey there 👋 thanks for your feedback 🤗

This example between chess and Super Mario Bros to explain the difference is simplification so that people get the big picture. On the one hand you have access to the whole checkboard on the other hand you see only a frame from the total level. The reality is more complex than that but it gives them a big idea of the difference between state/obs. That's why I will not update it.

For people who want to go deeper, we provide in additional links to more advanced introductions.

I'm closing this issue, thanks again 🤗

**Comment by andraxin** [comment]
@simoninithomas   
Since you're talking about a checkerboard instead of a **chess**board,  
maybe you should replace _chess_ with _checkers_, since AFAICT the latter
doesn't need extra state beyond the current board position, while the former does.

**Comment by simoninithomas** [comment]
I'm adding replacing to a checkboard in the todolist then
