### ISSUE TITLE
Explain how to use bash commands in Jupyter

### ISSUE THREAD

**Issue by osanseviero** [huggingface/deep-rl-class#145]
See https://github.com/huggingface/deep-rl-class/pull/143

**Comment by simoninithomas** [comment]
Thinking more about that I think I will not update the hands-on.mdx because it would **add more confusion.**

Since:
1. People that will use the colab already have !
2. Most of people wanted to run on their own notebook on their machine will use a copy of the ipynb
3. People who will really copy and paste the code will either
a. Know that they need to add !
b. If they don't know search on StackOverflow (button search on StackOverflow) or ask but given they already used notebooks before big majority will know about !.

Closing this issue for now,
