### ISSUE TITLE
Unit 1 - Add Monitor wrapper

### ISSUE THREAD

**Issue by CloXD** [huggingface/deep-rl-class#229]
Hello! 
First of all, thanks for this fantastic course, I'm really enjoying it! 
I'm running it locally and in the first unit, at the evaluation step, the package is complaining about the absence of a monitor wrapping the environment.
This could solve the complain:
```
eval_env = gym.make("LunarLander-v2")
from stable_baselines3.common.monitor import Monitor
eval_env_monitor = Monitor(eval_env)
mean_reward, std_reward = evaluate_policy(model, eval_env_monitor, n_eval_episodes=10, deterministic=True)
print(f"mean_reward={mean_reward:.2f} +/- {std_reward}")
```
Or in a more compact way
```
from stable_baselines3.common.monitor import Monitor
eval_env = Monitor(gym.make("LunarLander-v2"))
mean_reward, std_reward = evaluate_policy(model, eval_env, n_eval_episodes=10, deterministic=True)
print(f"mean_reward={mean_reward:.2f} +/- {std_reward}")
```
If it's a common issue, I can pull the change.
Cheers,
Claudio

**Comment by simoninithomas** [comment]
Hey there Claudio my apology for the miss of response. 

Regarding the issue of the absence of a monitor wrapping the environment, We point in the course (additional readings) documentation of the stable-baselines3 library, which provides more information about the use of monitors in reinforcement learning. The Monitor class is used to track and record the performance of the agent during training and evaluation. While it's not strictly necessary, it can be helpful for analyzing and understanding the agent's behavior.
Since it's not strictly necessary we didn't put it.

Have a nice day 🤗
