### ISSUE TITLE
[HANDS-ON BUG] Package to hub submission with a2c-PandaReachDense-v3 taking too log

### ISSUE THREAD

**Issue by Oladotun** [huggingface/deep-rl-class#463]
# Describe the bug

**Please share your notebook link so that we can reproduce the error**

I have a model trained for the Actor Critic model in Colab but when I try to use the package to hub command it has taken over one hour to be uploaded. Please find the link to the notebook in my google drive, here : https://colab.research.google.com/drive/1cNckWMiP3DCejQuw7zJ01B1hYAcw8K_c?usp=sharing . Kindly help

# Material

 - Did you use Google Colab? 
 - Yes

**Comment by simoninithomas** [comment]
Hey there 👋 the procress to upload with Panda Gym is approximately 10min (not because of the Hub but because of the Panda Gym lib).

From what I see the upload speed is super slow it might comes from either your internet connection or it was during a downtime of the hub.


![image](https://github.com/huggingface/deep-rl-class/assets/13088472/871fbab0-56ac-4e7d-b468-9572471d5c54)


In any case I saw you succeed to upload it: https://huggingface.co/Dotunnorth/a2c-PandaReachDense-v5
