### ISSUE TITLE
Unit 2 Notebook epsilon_greedy_policy Missing Parameter

### ISSUE THREAD

**Issue by forrestmckee** [huggingface/deep-rl-class#54]
In the unit 2 notebook, `epsilon_greedy_policy` is missing a parameter.
In the solution, `env.action_space.sample()` is called in the `else` condition. However, `env` is not in `epsilon_greedy_policy`'s scope.

```
def epsilon_greedy_policy(Qtable, state, epsilon):
  # Randomly generate a number between 0 and 1
  random_int = random.uniform(0,1)
  # if random_int > greater than epsilon --> exploitation
  if random_int > epsilon:
    # Take the action with the highest value given a state
    # np.argmax can be useful here
    action = np.argmax(Qtable[state])
  # else --> exploration
  else:
    action = env.action_space.sample()
  
  return action
```

Adding `env` to the function definition and function calls should fix this bug.

Thanks!

**Comment by simoninithomas** [comment]
Hey there (sorry for the delay) 🤗 ,

Indeed we **didn't pass the environment in the function because for this notebook we consider it as global variable.** 

Especially because this function is called only during the training. 

But indeed, as a good practice it's better to pass it as a parameter of the function.
