### ISSUE TITLE
Unit 2 - Bellman Equation - Value State Figure misleads reader

### ISSUE THREAD

**Issue by EvanMath** [huggingface/deep-rl-class#73]
Hello,

In this figure https://huggingface.co/blog/assets/70_deep_rl_q_part1/bellman2.jpg there are 6 rewards of -1 but in the equation below the value-state is calculated to -7. 

Would you like to see again the figure?

Regards

**Comment by jackvial** [comment]
@EvanMath Yes it should be -6, Thomas confirm here on discord [here](https://discord.com/channels/879548962464493619/976519349684797510/980458487563841557)

**Comment by osanseviero** [comment]
Hey there! Thanks for the report! @simoninithomas should we change the blog post image?

**Comment by simoninithomas** [comment]
Yes. I'm adding it to my today todo list thanks 🤗

**Comment by EvanMath** [comment]
Ok, cool. Thank you, guys!

**Comment by unverciftci** [comment]
But there is still inconstancy with the values. In the previous figure the vaule is -7. Also the rewards of this porblem should be stated explicitly. For instance, what is the reward of the terminal state?

**Comment by simoninithomas** [comment]
The reward of the terminal state is -1. But the fact that the cheese is outside of the grid can mislead the reader (the idea is that the cheese was on the -1 state but because it hides the value I put it outside) Yes there is still the error in the grid (the one that shows the whole grid). There will be a rewamp of this example for the new batch of the course.
